### ISSUE TITLE
SW notes

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/whattheflux#25]
- [x] Remove wtf_fill_metadata #26 
- [x] Plot is arbitrary, could be bottle, etc. #27 
- [x] Add area and volume to flux calculation #29 
- [x] No defaults in fill fn
- [ ] Example of processing multiple files
- [ ] QA/QC of lots of msmts
- [x] Integration of gasfluxes - vignette #31 
- [ ] Deadband sensitivity analysis - vignette?
